# PUnit example project #######################################################

# Add here one or more source code directories.
# PUnit will automatically build those modules that are testable by implemented
# tests.
SRCDIR = ./

# Add here one or more include directories.
IDIR = ./

# Set this to 1 if you will use asserts that compares floats or doubles
PU_LMATH = 1

CCFLAGS =

# DO NOT TOUCH
include ../punit/Makefile.punit
