# PUnit example project #######################################################

# Add here one or more source code directories.
# PUnit will automatically build those modules that are testable by implemented
# tests.
SRCDIR = ./

# Add here one or more include directories.
IDIR = ./

# Set this to 1 if you will use asserts that compares floats or doubles;
# or 0 disable
PU_LMATH = 1

# Enable Unix Unit (incl. stdin_writer)
PU_UU = 1

# Report oriented mode prints more additional information like test module and
# test case descriptions. 0 = disabled; 1 = enabled.
PU_REPORT_ORIENTED = 1

CCFLAGS =

# DO NOT TOUCH
include ../punit/Makefile.punit
