# PUnit example project #######################################################

# Add here one or more source code directories.
# PUnit will automatically build those modules that are testable by implemented
# tests.
SRCDIR = ./

# Add here one or more include directories.
IDIR = ./

# DO NOT TOUCH
include ../punit/Makefile.punit
